In [1]:
import pandas as pd
import re
import json

In [2]:
df = pd.read_excel('../data/Broken Bells Songs.xlsx')
df.head()

,Song,Album,Year,Writers,Unnamed: 4,Version Type,Notes
0,The High Road,Broken Bells,2009,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN,NaN
1,Vaporize,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN,NaN
2,Your Head Is On Fire,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN,NaN
3,The Ghost Inside,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN,NaN
4,Sailing to Nowhere,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN,NaN

In [3]:
df = df.drop(columns=['Compilation?', 'Unnamed: 4'], errors='ignore')
df = df.rename(columns={'Version Type': 'Version_Type'})
df.head()

,Song,Album,Year,Writers,Version_Type,Notes
0,The High Road,Broken Bells,2009,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN
1,Vaporize,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN
2,Your Head Is On Fire,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN
3,The Ghost Inside,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN
4,Sailing to Nowhere,Broken Bells,2010,James Mercer (age 37 - 39); Brian Burton (age ...,NaN,NaN

In [4]:
def parse_writers(value):
    if pd.isna(value):
        return []
    writers = []
    for entry in str(value).split(';'):
        entry = entry.strip()
        match = re.match(r'^(.+?)\s*\(age\s*(.+?)\)$', entry)
        if match:
            writers.append({
                'name': match.group(1).strip(),
                'age': match.group(2).strip()
            })
        else:
            writers.append({'name': entry, 'age': None})
    return writers

df['Writers'] = df['Writers'].apply(parse_writers)
df[['Song', 'Writers']].head(10)

                   Song                                            Writers
0         The High Road  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
1              Vaporize  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
2  Your Head Is On Fire  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
3      The Ghost Inside  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
4    Sailing to Nowhere  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
5            Trap Doors  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
6               Citizen  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
7               October  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
8         Mongrel Heart  [{'name': 'James Mercer', 'age': '37 - 39'}, {...
9   The Mall and Misery  [{'name': 'James Mercer', 'age': '37 - 39'}, {...

In [6]:
string_cols = ['Song', 'Album', 'Version_Type', 'Notes']
for col in string_cols:
    df[col] = df[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

df.head()

,Song,Album,Year,Writers,Version_Type,Notes
0,The High Road,Broken Bells,2009,"[{'name': 'James Mercer', 'age': '37 - 39'}, {...",NaN,NaN
1,Vaporize,Broken Bells,2010,"[{'name': 'James Mercer', 'age': '37 - 39'}, {...",NaN,NaN
2,Your Head Is On Fire,Broken Bells,2010,"[{'name': 'James Mercer', 'age': '37 - 39'}, {...",NaN,NaN
3,The Ghost Inside,Broken Bells,2010,"[{'name': 'James Mercer', 'age': '37 - 39'}, {...",NaN,NaN
4,Sailing to Nowhere,Broken Bells,2010,"[{'name': 'James Mercer', 'age': '37 - 39'}, {...",NaN,NaN

In [7]:
df.to_json(
    '../data/broken-bells-songs.json',
    orient='records',
    force_ascii=False,
    indent=2
)
print("JSON exported successfully!")

JSON exported successfully!

In [8]:
with open('../data/broken-bells-songs.json', 'r') as f:
    print(f.read(500))

[
  {
    "Song":"The High Road",
    "Album":"Broken Bells",
    "Year":2009,
    "Writers":[
      {
        "name":"James Mercer",
        "age":"37 - 39"
      },
      {
        "name":"Brian Burton",
        "age":"30 - 31"
      }
    ],
    "Version_Type":null,
    "Notes":null
  },
  {
    "Song":"Vaporize",
    "Album":"Broken Bells",
    "Year":2010,
    "Writers":[
      {
        "name":"James Mercer",
        "age":"37 - 39"
      },
      {
        "name":"Brian Burton",
        "