In [1]:
import pandas as pd
import re
import json

In [2]:
df = pd.read_excel('../data/Depeche Mode Songs.xlsx')
df.head()

,Song,Album,Year,Writers,Unnamed: 4,Version Type,Notes
0,New Life,Speak and Spell,1981.0,Vince Clarke (age 20 - 21),NaN,NaN,NaN
1,I Sometimes Wish I Was Dead,Speak and Spell,1981.0,Vince Clarke (age 20 - 21),NaN,NaN,NaN
2,Puppets,Speak and Spell,1981.0,Vince Clarke (age 20 - 21),NaN,NaN,NaN
3,Boys Say Go!,Speak and Spell,1981.0,Vince Clarke (age 20 - 21),NaN,NaN,NaN
4,Nodisco,Speak and Spell,1981.0,Vince Clarke (age 20 - 21),NaN,NaN,NaN

In [3]:
df = df.drop(columns=['Compilation?', 'Unnamed: 4'], errors='ignore')

In [4]:
def parse_writers(value):
    if pd.isna(value):
        return []
    writers = []
    for entry in str(value).split(';'):
        entry = entry.strip()
        match = re.match(r'^(.+?)\s*\(age\s*(.+?)\)$', entry)
        if match:
            writers.append({
                'name': match.group(1).strip(),
                'age': match.group(2).strip()
            })
        else:
            # Writer listed with no age (e.g. Andrew Phillpott)
            writers.append({'name': entry, 'age': None})
    return writers

df['Writers'] = df['Writers'].apply(parse_writers)
df[['Song', 'Writers']].head(10)

                          Song                                       Writers
0                     New Life  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
1  I Sometimes Wish I Was Dead  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
2                      Puppets  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
3                 Boys Say Go!  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
4                      Nodisco  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
5            What's Your Name?  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
6                 Photographic  [{'name': 'Vince Clarke', 'age': '20 - 21'}]
7            Tora! Tora! Tora!   [{'name': 'Martin Gore', 'age': '19 - 20'}]
8                     Big Muff   [{'name': 'Martin Gore', 'age': '19 - 20'}]
9      Any Second Now (Voices)  [{'name': 'Vince Clarke', 'age': '20 - 21'}]

In [5]:
string_cols = ['Song', 'Album', 'Version_Type', 'Notes']
for col in string_cols:
    df[col] = df[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

df.head()

KeyError: 'Version_Type'

In [ ]:
df = df.drop(columns=['Compilation?', 'Unnamed: 4'], errors='ignore')

In [ ]:
df.to_json(
    '../data/depeche-songs.json',
    orient='records',
    force_ascii=False,
    indent=2
)
print("JSON exported successfully!")

In [ ]:
with open('../data/depeche-songs.json', 'r') as f:
    print(f.read(500))